version: '3'
services:
  db:
    image: mysql:latest
    container_name: soco_db
    environment:
     MYSQL_USER: root
     MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  web:
    build: .
    image: server_api
    container_name: server_api
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./SocoAPI:/var/www/html/SocoAPI
    ports:
      - "3000:3000"
    depends_on:
      - db